### ISSUE TITLE
Progress discussion

### ISSUE THREAD

**Issue by enumag** [07th-mod/himatsubushi#1]
@ItaloKnox Let's move the discussion about himatsu here,

I've run the voice inserter on Himatsu and pushed the result (https://github.com/07th-mod/himatsubushi/commit/7e4fc77a33fd59f93c87d31961c19fa052a83955). Here is the report:

```
Inserted 0 voice lines to flow.txt.
Inserted 478 voice lines to hima_001.txt.
Inserted 112 voice lines to hima_002.txt.
Inserted 107 voice lines to hima_002_02.txt.
Inserted 464 voice lines to hima_002_03.txt.
Inserted 160 voice lines to hima_003.txt.
Inserted 85 voice lines to hima_003_02.txt.
Inserted 272 voice lines to hima_003_03.txt.
Inserted 150 voice lines to hima_003_04.txt.
Inserted 107 voice lines to hima_003_05.txt.
Inserted 275 voice lines to hima_004.txt.
Inserted 23 voice lines to hima_tips_01.txt.
Inserted 0 voice lines to hima_tips_02.txt.
Inserted 0 voice lines to hima_tips_03.txt.
Inserted 15 voice lines to hima_tips_04.txt.
Inserted 25 voice lines to hima_tips_05.txt.
Inserted 1 voice lines to hima_tips_06.txt.
Inserted 40 voice lines to hima_tips_07.txt.
Inserted 31 voice lines to hima_tips_08.txt.
Inserted 2 voice lines to hima_tips_09.txt.
Inserted 35 voice lines to hima_tips_10.txt.
Inserted 2 voice lines to hima_tips_11.txt.
Inserted 12 voice lines to hima_tips_12.txt.
Inserted 0 voice lines to hima_tips_13.txt.
Inserted 4 voice lines to hima_tips_14.txt.
Inserted 0 voice lines to init.txt.
Inserted 286 voice lines to omake_04.txt.
```

Let me know if you find anything that you think should have been caught by the script.

**Comment by enumag** [comment]
I've added a readme to the [voice inserter](https://github.com/07th-mod/voice-inserter) repo with instructions how to run it. I don't think anyone other than me will need to use it anytime soon but whatever.

**Comment by ItaloKnox** [comment]
Looks great! I should start working on it later today. I guess this is going to be a nice chapter to work on.

**Comment by enumag** [comment]
Oh you've finished all the tips already? You really work fast! Great work! :-)

**Comment by ItaloKnox** [comment]
They were pretty easy, got them finished while waiting for my cat to return from the vet. 😆 

The real thing starts now. My goal is to finish at least three scripts a day.

**Comment by DoctorDiablo** [comment]
I put together the basic sprites+backgrounds graphics patch for Himatsu: http://www.mediafire.com/file/cxn386i9kc4ee95/Higurashi+Ch.4+-+PS3+Graphics+Mod+1.0.rar

A decent number of the backgrounds had no equivalent in the PS3 assets, so I just did my best to use the closest thing.  We'll have to make script changes to get the backgrounds fully synced up with the PS3 version.  There were a couple weird little things unique to this episode like one bg that is double-height (640x960) and does a vertical pan.  When we add the CGs, we can sort out those things.

One thing I _expected_ to be an issue but turned out no problem: In the PS3 version Rika and Mion have separate child sprites for the 1978 scenes but use their regular sprites in the omake scene, while in the original they use the same sprites for everything.  Luckily, there's no overlap between those so I just had to overwrite the appropriate sprites.

**Comment by Grelo** [comment]
Ok guys i completed Scenarios for Higurashi Question Arcs, you can use it for previous chapters too if you want.....i created it from scratch to be at least similar to Guras. Enjoy!

https://mega.nz/#!JcNAkTQJ!MkRMm6S0UPEo2zYmh5VrIo4dRtLbnTJ1p2p5NWC2JRI

**Comment by enumag** [comment]
@Grelo When you post a link don't put it in square brackets with "(url)" - the link doesn't actually work then. Just paste it normally.

**Comment by Grelo** [comment]
@enumag Good to know, but is it working?

**Comment by enumag** [comment]
@Grelo The link itself is fine it just wasn't clickable and I had to copy it manually. Until I edited it for you. ;-)

**Comment by Grelo** [comment]
@enumag Thanks. Now to wait for ItaloKnox to finish scripts and direct road on Himatsu :)

**Comment by marakeusz** [comment]
I am curious if you are going to release voice only patch first or it will be only voice + graphic option?

**Comment by ItaloKnox** [comment]
@marakeusz voices first because it's a feature always requested a lot. But they might be released in the same week or a week after, at least the simple graphics (BGs + sprites) are already completed, so after that it's only a matter of adding the CGs and tweaking the scenes.

Btw, progress stalled in this weekend but the patch should be finished in a few days. Maybe by thursday it should be already released and stable.

**Comment by Grelo** [comment]
@DoctorDiablo Are you sure you have no mistakes in your graphic mod? I just peeked for a little in it and found u have using exactly same sprite under name "ri_se_fu_a1" and "ri_si_fu_a1" . Just asking. :)

**Comment by DoctorDiablo** [comment]
Yep, that was intentional.  It fixes an error in the original script.  That particular sprite is only used once, and it should be using the 5 year old Rika sprite instead of the 10 year old Rika.

It would probably make more sense to update the script to use the ri_si sprite, but I was packaging it as a graphics-only release.

**Comment by Grelo** [comment]
@DoctorDiablo Its fine i can work with "ri_se" too when ill begin doing it. Just to be sure there are no big mistakes, thanks.

**Comment by ItaloKnox** [comment]
Ok, guys, voice patch is now finished and already uploaded to the repo. I'm going to push a release tomorrow, so first we need to sort out some details.

Since we're gradually improving the graphics patch instead of releasing it 100% complete, I suggest that every graphics update should become an incremental patch. That means, when we add something new to the graphics, instead of uploading a whole new patch you guys should only upload what's new.

So, based on that, we're starting with @DoctorDiablo's patch and merging with @Grelo's scenarios. I'll merge every new addition and upload it to [07th-mod/resources](https://github.com/07th-mod/resources/releases). For the sake of archiving, it's more secure to host the files at github in case MEGA or MediaFire have unexpected issues (we all know what happened to Megaupload).

I'll also work on a general wiki to avoid clutter and keep things updated for all chapters at once, it should be available on [07th-mod/guide](https://github.com/07th-mod/guide/wiki) sometime soon. Any help would be appreciated.

**Comment by Grelo** [comment]
Tatadaaaaaaaa! Full PS3 Graphic mod below (voices in scripts too). Enjoy! 
Now long break form Higu :(

https://mega.nz/#!dNUgwRIJ!GJGTsiv3G1FMu0MnKT4Jcv01b_nJIUtyR48309Y0aW0

**P.S.** The last day (last script) contains exclusive dialog with Akasakas daughter at the beginning, i think you should include it in some way later so i can put her sprites in + last lines of novel have voices in PS3 version so if you could check that it would be great, have a nice day :)

**Comment by ItaloKnox** [comment]
Awesome! Our translator will probably go through the novel and fix everything like he did with Onikakushi and Watanagashi, but I suppose it won't be that fast since we could only _really_ finish Tatarigoroshi a week ago and he still didn't went through it. Anyway, it should happen sooner or later.

By the way, that's the 1080p patch, right? Would it be too much if I asked you to update the 720p patch? Shouldn't be really an issue if you don't, we can just stick with the 1080p patch from now on, which IMO is preferred.

**Edit:** just gave some thought about this. What do you guys think about sticking with 1080p mods from now on? Should be an improvement even for people playing it in 720p widescreen. We already have all patches to make this transition, I think it shouldn't be a problem and even better in the long run.

**Comment by enumag** [comment]
@ItaloKnox :+1: for 1080p patches from now on.

@Grelo Awesome work! I'm really looking forward to this once I'm done with Tatari. Would you be willing to make 1080p patches for Onikakushi and Watanagashi as well? Not necessarily now, just someday. It would be nice to have all episodes like that. ;-)

**Comment by Grelo** [comment]
@enumag Its already made, i uploaded it few days ago in tatari discussion
@ItaloKnox I would need to make it from scratch, if u are for i vote for 1080p :-)

**Comment by ItaloKnox** [comment]
Then great, let's keep the 1080p patches. The zips are a little too big to keep on Github and maybe not really worth making it into a few parts, so I guess it should be ok to keep them in MEGA for a while. Megaupload should be coming back early next year, so I can migrate everything then.

**Comment by Kamlingen** [comment]
@ItaloKnox Did you add 440400273 with a mistake or was it correct? (omake_04)

**Comment by ItaloKnox** [comment]
My bad, the script was right but I forgot to commit the new file.

**Comment by Kamlingen** [comment]
These haven't been fixed.

https://github.com/07th-mod/himatsubushi/issues/5#issuecomment-256261322
https://github.com/07th-mod/himatsubushi/issues/5#issuecomment-256261662

**Comment by ItaloKnox** [comment]
I fixed them but it seems it wasn't committed. Should be already uploaded now.

**Comment by DoctorDiablo** [comment]
Checked in some spellcheck fixes for Hima.  It had noticeably more findings than Tata, even though it's half as long.  Mangagamer must be skimping on their proofreading.

**Comment by ItaloKnox** [comment]
Nice, should be enough to push a new release for Tata and Hima. Thanks!
