### ISSUE TITLE
Couldnt download the ghrapics mod

### ISSUE THREAD

**Issue by gagantous** [07th-mod/himatsubushi#11]
could you change the dl site to another file sharing like mediafire, mega, or google drive, since i couldnt download the ghrapics mods file via IDM. its keep dowloading using browser.

thank you

**Comment by ItaloKnox** [comment]
You probably need an extension like FlashGot to properly download the file on Firefox. If you are using Chrome or any other browsers, try looking for an alternative. Unfortunately we can't make mirrors since the link we use now build the patch right after you click on it, so you can always get the latest files.
