### ISSUE TITLE
Some Issues for Hima

### ISSUE THREAD

**Issue by orian34** [07th-mod/himatsubushi#35]
WIP:
Missing Day on the chapter menu : 
![image](https://user-images.githubusercontent.com/12663654/42850438-e689f314-8a27-11e8-9348-ab6eb695848f.png)

WIP:
No differentiation for the Mother's diary tips, when there is in the unlock menu, add numbers?
![image](https://user-images.githubusercontent.com/12663654/42850933-50e59644-8a2a-11e8-8896-11d6827e3fc6.png)
![image](https://user-images.githubusercontent.com/12663654/42852130-7514a1a4-8a2f-11e8-9cce-5414812acac2.png)

SOLVED:
And the most tricky one, about a number of missing voice lines in the Omake. I got them in the voices folder, but I don't understand japanese, and they might be longer than the text, and I don't know what fits on what sentence. I'd need Norgus' help on this possibly, to know how best to implement them.
https://github.com/07th-mod/himatsubushi/blob/ab4cf3e30cb11241b3d4b99b113ed23c633d0522/Update/omake_04.txt#L2669

The missing voice lines numbers would be from 
ps3/s20/02/440200343 to ps3/s20/02/440200345
ps3/s20/02/440200349 to ps3/s20/02/440200352

WIP:
![image](https://user-images.githubusercontent.com/12663654/42852071-2948a950-8a2f-11e8-94a2-a87c6e5053bb.png)
Girl becomes Chick in the tips menu. To be chick.

WIP:
What about this? We don't have the picture? 
I feel like it could be nice to have it.
Here's the link and the pictures.
https://youtu.be/BQyKROV-KbM?list=PLt1PMnqoYKpQoPFjH-oVpDKhwc7_I7xFp&t=1402
![image](https://user-images.githubusercontent.com/12663654/43332341-6fba017c-91c8-11e8-8f72-12faed3b14e1.png)
The current script only writes it like a normal line. It happens at the very end of Day 4.

**Comment by ghost** [comment]
>Girl becomes Chick in the tips menu, which one is the correct one?

Should be chick (like a young chicken) because there's there's no girl in the trunk.

**Comment by enumag** [comment]
@idealpersona The missing "Day" in chapter menu and missing number in tips are both DLL things, right? Can you fix those?

@Norgus Could you look into the missing voices?

@jwgrlrrajn The screen with "The Girl in the Trunk" typo is a unlocked tips image `hima001.png`. Can you create a new one using Inochi's PSD? Here is the current one for reference.

![hima001](https://user-images.githubusercontent.com/539462/42897224-9efba446-8abf-11e8-9a83-bcfa28885091.png)

**Comment by ghost** [comment]
@enumag There's a prefab for the chapter screen; none of the text appears to be hard-coded.  A fix for that probably requires editing the resource pack.

The tips will be editable as they are currently hard-coded.  I would want to take this chance to integrate tips.json - the code is already there for Hima on a branch, but we will have to figure out how those files will be managed for installation.  I know @DoctorDiablo planned to integrate it for the Tarai release so he might already have a pattern figured out that we can follow.

**Comment by enumag** [comment]
@idealpersona Alright, I'll try to check the resource pack later then.

Integrating a tips.json it not related to the typo posted here. The screen is just an image, not buttons that can be clicked. We could try to change it to be that way but then the labels would be in the script and not in tips.json either (unless there was command to pull the labels from there). Anyway tips.json is not relevant here for now.

**Comment by ghost** [comment]
@enumag I think you might be misunderstanding; this is indeed in the code.  Unless by "typo" you meant something else?  The discrepancy arises when someone mouses over one of the 3 "Mother's Diary" tips in the menu and sees the same "Mother's Diary" label for each one on mouseover.  This is driven by the code below.

![image](https://user-images.githubusercontent.com/36429889/43016302-ab57a338-8c0f-11e8-8453-5284e16a9c86.png)

If there were a problem in the screenshot with the red images labeling I, II, and III, then yeah that wouldn't relate to the DLL.  But things like this are one of the benefits of having tips in a separate text file, so that's why i was suggesting to integrate it here.

**Comment by ghost** [comment]
Regarding the "trunk" tip title, looks like the 雛 in the title "トランクの雛" indicates "chick" is the intended translation.

**Comment by enumag** [comment]
Oh sorry, You're right I misunderstood. :-) tips.json will be nice here.

**Comment by Norgus** [comment]
So, I looked at the mentioned missing voices and concluded that they are too different (and specific to the PS3 game system) to include.

I also commented out a few surrounding voices since they kind of contradict what the text actually says.
1ee8ec2f0c3661a17650445ecce59bcb782c53e7

re the removed voices:
440200340 talks about how the system changed to include choices
440200341 mentions how the order you read chapters might be changed depending on those choices
440200342 acknowledges how this change might be discomforting for fans of the original
440200348 is just completely different wording (instead of saying next is the answer arc, it is worded more like "now we finally enter the mid-point"

**Comment by orian34** [comment]
Added another bit.

**Comment by enumag** [comment]
Missing "Day" in the chapter jump is a won't fix for now because we have no idea where those texts are.

So the only thing left to fix here is the Mother's Day titles on tips screen. Can we fix that now with the json, @idealpersona ?

**Comment by ghost** [comment]
@enumag Yeah we can - just gotta get that whole branch of code integrated into the mainline and prepare a baseline nipah.json into all the arcs, or at least this one.  That would include source control and installation, but I don't know much about the installation procedures.

**Comment by enumag** [comment]
@idealpersona Just prepare the DLL and JSON, @ItaloKnox can handle the installation changes.

**Comment by orian34** [comment]
separated the issues
