### ISSUE TITLE
Question: Would it be possible for an update-only graphics pack download?

### ISSUE THREAD

**Issue by Branleace** [07th-mod/himatsubushi#9]
The graphics packs are getting pretty large now and many images are copies from previous chapters.  I've just been stuffing the graphics and voices in (../Documents/Higurashi Assets/CGAlt) and (/SE) and making symlinks to those to replace the originals for each release.  I just hated having 4 copies of several of the backgrounds which (seemingly) unnecessarily increases the length of the downloads.

I was just wondering if it would be possible to have a download option that only contains new portraits/cgs/backgrounds for each release to cut down the download time and bandwidth usage.  The current option makes sense for those that only keep one chapter installed at a time, I was just hoping for a quicker option for those of us that keep previously installed chapters and assets.  Thanks for all your hard work on these.

**Comment by ItaloKnox** [comment]
I can definitely look into that. I also share the same concern as you, but it's already a little too late to go with symlinks as the default method and then deliver only the updates. **Though** I think I have an idea on how to fix this issue and make everyone happy, except it won't be as simple as downloading a zip, but should be easy enough for someone who can set up symlinks.

I'll need to run a couple of tests first and then see if it works as intended, so keep an eye on this thread. I should have a definitive answer until this weekend.

**Comment by Branleace** [comment]
Awesome, thanks.  No rush for me as I'm caught up, but definitely would like to see how it'll be implemented going forward if at all.

**Comment by ItaloKnox** [comment]
Didn't take as long as I expected. The solution for that was to go with git to deliver updates and have the end users only getting the newest files instead of downloading the whole thing again.

The pros is that you can now keep a CGAlt folder that will be updated often with new chapters and bugfixes, the cons is that you'll have to download the whole thing again with git to make it work.

To get the repository with all the graphics, run `git clone https://gitlab.com/07th-mod/higurashi-graphics.git` where you want to store the files and then symlink the whole thing again. If you aren't familiar with git, to grab the latest updates you just have to run `git pull` inside the folder.

I guess this should work fine, but I didn't take my time to properly check all the files. My work is pretty much done remotely, so I can't count on a graphical interface to double check everything.

Anyway, I'll update the wiki with proper instructions and all that jazz sometime soon. Since you already went as far as to build your own symlinks, this should be a breeze. If you have any questions, just reopen the issue and I'll be glad to help!

**Comment by Branleace** [comment]
Thanks, and I am quite familiar with git and version control as a software engineer, but thanks for the information nevertheless.  While this would solve the bandwidth issue, binaries in version control can be dangerous when trying to conserve storage space.  Of course, as long as end users use shallow clones or there are no huge overhaul pushes, I don't imagine it would be bad and would make this a great solution.

I am, however, experiencing issues cloning.  It seems the server is timing out after 30 minutes.  The steps I took to clone it were: cd into my CGAlt folder, use the `git clone --depth 1 https://gitlab.com/07th-mod/higurashi-graphics.git .`command, it goes through the counting and compressing of 1412 files, downloads at an average 1.8 MiB/s, then after ~30 minutes and around 2-3 GB it gives "fatal: The remote end hung up unexpectedly", "fatal: early EoF", and "fatal: index pack failed", then it tries to delete my directory.

Maybe I'm foolishly overlooking something, but it seems to be an issue with gitlab not giving enough time for the very large repo.

**Comment by ItaloKnox** [comment]
Seems to be a client-related issue. Try running `git config http.postBuffer 524288000` and then cloning the repository again. If that doesn't work I'll need to make a workaround to use SSH access.

**Comment by enumag** [comment]
@ItaloKnox Just out of curiosity, why did you put the repository to gitlab instead of github?

**Comment by ItaloKnox** [comment]
Gitlab has a 10gb limit for repositories while Github can keep only 1gb. It's currently the best way (and free) of updating/delivering the graphics patch.

I thought about starting a "donation drive" every time a new chapter is released to open our own server and run our own git server, but it seems Gitlab will do the job for a while. Since the project is quite popular, I think it wouldn't be too hard to start our own server at the cheapest kimsufi, but I guess it's better we try our best to keep it as free as possible without being a bother to development.

**Comment by Branleace** [comment]
Well, I hit the wall again, but this time it was after 45 - 50 minutes and between 4 and 5 GB.  I have space on my hard drive, my internet has been solid and I have no firewalls or anything that should interfere.  Here's exactly as it appears:

![git](https://cloud.githubusercontent.com/assets/13204438/19978881/7ade5f10-a1c6-11e6-911c-bd37bc4a57ee.png)

My sincere apologies if this really is something silly on my end, but I appreciate your work.  I'll try editing the buffer size again, doubling it once, to see if that affects it.

I'd also love to throw some money at you guys to support all of this great work if you do decide to go the server route in the future.  I would imagine you guys would have begun a Patreon or something by now.

**Comment by ItaloKnox** [comment]
It's not actually your fault, but more like git's fault. I guess the repository is too big for git to handle smoothly without big speeds of 10mb/s or more. I'm going to take a look at SSH, it _should_ fix the issue. Give me an hour to see what I can do.

**Comment by ItaloKnox** [comment]
Actually I think I got an easier way to fix this. We just have to double the buffer value I posted above: `git config --global http.postBuffer 1048576000`. This should definitely work.

**Edit**: to further elaborate the issue, it really seems to be related to the download speed. My remote cloned the repo without touching the buffer.

![](https://2.lithi.io/qeN8MT.png)

**Comment by Branleace** [comment]
Unfortunately, it didn't work.  It died just before 5 GB I began it again a minute or two after your last reply, so after just about an hour.

![git2](https://cloud.githubusercontent.com/assets/13204438/19983167/e4509cb4-a1d6-11e6-84fa-90d0c01b4f05.png)

The reason the deletion message is broken is because I hit the enter key a few minutes after it began.

I totally understand if you'd like to put this on the back burner for now as we have months before the next release and this likely isn't a huge concern.  Thanks.

**Comment by ItaloKnox** [comment]
Well, that sucks. I'll keep looking into SSH, the main issue is that SSH can only be accessed with a certain public key, so I need to set up an account just for that. I'll see what I can do.

**Comment by ItaloKnox** [comment]
I did my best to find a way of properly fixing this but it seems to be impossible without setting up our own git server. If you are stuck by a lower speed, you'll most likely get beaten by the timeout.

Git isn't actually the proper way of delivering this kind of content, so I'll try to look for something else. Maybe some kind of patcher thing, but this will take a lot longer to develop.

**Comment by Branleace** [comment]
Understandable.  I was a tad wary of using git to begin with.  My experience lies mostly in C/C++ and a little in writting a database program that auto-updated (though it was a quick and dirty project), so I'll see if I can come up with a possible solution in the meantime, too.  Thanks.

**Comment by enumag** [comment]
With the recent changes we have made I don't think we need to do something like this. The installers from @ItaloKnox provide much simpler way to install and update the patches than previously. And the compressed images from @Grelo make the patch much smaller.
